import type {
  EvidencePassage,
  EvidenceSnapshot,
  OriginAssessment,
  OriginFacet,
  SourceClaimVersion,
  TemporalFinding,
} from "./types";

interface FacetCandidate {
  snapshot: EvidenceSnapshot;
  version: SourceClaimVersion;
  passages: EvidencePassage[];
  confidence: number;
  evidenceIds: string[];
}

const EXPLICIT_ORIGIN =
  /\b(?:first (?:posted|published|appeared|shared|uploaded)|originally (?:posted|published|shared|uploaded|created|generated)|created by|generated by|originated (?:with|from)|source of (?:the )?(?:claim|rumou?r|image|photo|video))\b/i;
const MISINFORMATION_CONTEXT =
  /\b(?:misinformation|false claim|rumou?r|hoax|fake|fabricated|ai[- ]generated|synthetic|misleading|viral claim)\b/i;

function clamp(value: number): number {
  return Math.max(0, Math.min(1, value));
}

function round(value: number): number {
  return Math.round(clamp(value) * 1000) / 1000;
}

function unique(values: string[]): string[] {
  return [...new Set(values.filter(Boolean))];
}

function emptyFacet(reason: string): OriginFacet {
  return {
    status: "insufficient_evidence",
    sourceId: null,
    confidence: null,
    evidenceIds: [],
    reason,
  };
}

function facet(
  candidate: FacetCandidate,
  status: OriginFacet["status"],
  reason: string,
): OriginFacet {
  return {
    status,
    sourceId: candidate.snapshot.id,
    confidence: candidate.confidence,
    evidenceIds: candidate.evidenceIds,
    reason,
  };
}

function bestVersionMap(versions: SourceClaimVersion[]): Map<string, SourceClaimVersion> {
  const bySource = new Map<string, SourceClaimVersion>();
  for (const version of versions) {
    const current = bySource.get(version.sourceId);
    if (!current || version.confidence > current.confidence) {
      bySource.set(version.sourceId, version);
    }
  }
  return bySource;
}

function candidateFor(
  snapshot: EvidenceSnapshot,
  version: SourceClaimVersion,
  passages: EvidencePassage[],
): FacetCandidate {
  const passageConfidence =
    passages.length > 0 ? Math.max(...passages.map((passage) => passage.relevance)) : 0.5;
  return {
    snapshot,
    version,
    passages,
    confidence: round(
      Math.min(version.confidence, snapshot.extractionConfidence, passageConfidence),
    ),
    evidenceIds: unique([
      snapshot.id,
      ...version.evidenceIds,
      ...passages.map((passage) => passage.id),
    ]),
  };
}

function originalEventFacet(
  snapshots: EvidenceSnapshot[],
  versions: SourceClaimVersion[],
): OriginFacet {
  const versionsBySource = bestVersionMap(versions);
  const candidates: FacetCandidate[] = [];

  for (const snapshot of snapshots) {
    if (snapshot.sourceType !== "primary" && snapshot.sourceType !== "official") continue;
    const version = versionsBySource.get(snapshot.id);
    if (!version) continue;
    const passages = snapshot.relevantPassages.filter(
      (passage) => passage.kind === "provenance" || passage.kind === "context",
    );
    candidates.push(candidateFor(snapshot, version, passages));
  }

  candidates.sort(
    (left, right) =>
      right.confidence - left.confidence || left.snapshot.id.localeCompare(right.snapshot.id),
  );
  const best = candidates[0];
  if (!best) {
    return emptyFacet(
      "No acquired primary or official source with an evidence-grounded claim version documents the underlying event.",
    );
  }

  const established =
    best.passages.length > 0 &&
    best.confidence >= 0.75 &&
    best.evidenceIds.length >= 2;
  return facet(
    best,
    established ? "established" : "candidate",
    established
      ? "A primary or official source with specific passages documents the underlying event. This does not establish where misinformation began."
      : "A primary or official event source was found, but its extracted evidence is not strong enough to establish the original event account.",
  );
}

function misinformationOriginFacet(
  snapshots: EvidenceSnapshot[],
  versions: SourceClaimVersion[],
): OriginFacet {
  const versionsBySource = bestVersionMap(versions);
  const candidates: FacetCandidate[] = [];

  for (const snapshot of snapshots) {
    const version = versionsBySource.get(snapshot.id);
    if (!version) continue;
    const passages = snapshot.relevantPassages.filter(
      (passage) =>
        passage.kind === "provenance" &&
        EXPLICIT_ORIGIN.test(passage.text) &&
        MISINFORMATION_CONTEXT.test(passage.text),
    );
    if (passages.length === 0) continue;
    candidates.push(candidateFor(snapshot, version, passages));
  }

  candidates.sort(
    (left, right) =>
      right.confidence - left.confidence || left.snapshot.id.localeCompare(right.snapshot.id),
  );
  const best = candidates[0];
  if (!best) {
    return emptyFacet(
      "No specific acquired passage establishes where the misleading version was first created or posted.",
    );
  }

  // Secondary reporting can identify an origin lead, but the reporting page is
  // not itself the original artifact. Only a social/primary artifact with
  // strong extraction is eligible to establish this facet.
  const isOriginalArtifact =
    best.snapshot.sourceType === "social" || best.snapshot.sourceType === "primary";
  const established =
    isOriginalArtifact && best.confidence >= 0.8 && best.evidenceIds.length >= 2;
  return facet(
    best,
    established ? "established" : "candidate",
    established
      ? "An acquired original artifact explicitly identifies creation or first posting in misinformation context."
      : "A source explicitly reports an origin, but the original artifact itself was not acquired strongly enough to establish misinformation origin.",
  );
}

function likelyOriginFacet(
  misinformationOrigin: OriginFacet,
  earliestRelevantSource: TemporalFinding,
): OriginFacet {
  if (misinformationOrigin.sourceId) {
    return {
      ...misinformationOrigin,
      status:
        misinformationOrigin.status === "established" ? "established" : "candidate",
      reason:
        misinformationOrigin.status === "established"
          ? "The strongest origin candidate is also supported as the acquired original misinformation artifact."
          : "This is the strongest origin candidate because a specific passage reports creation or first posting, but the original artifact remains unverified.",
    };
  }

  if (earliestRelevantSource.sourceId) {
    return {
      status: "candidate",
      sourceId: earliestRelevantSource.sourceId,
      confidence: earliestRelevantSource.confidence,
      evidenceIds: earliestRelevantSource.evidenceIds,
      reason:
        "The earliest relevant dated source is retained only as a likely-origin candidate. Earliest found is not the same as original source.",
    };
  }

  return emptyFacet("No evidence-backed origin candidate could be identified.");
}

/**
 * Keeps four questions separate: the underlying event source, earliest source
 * found, misinformation origin, and best origin candidate. In particular,
 * earliest search result is never promoted automatically to original origin.
 */
export function assessOrigin(
  snapshots: EvidenceSnapshot[],
  versions: SourceClaimVersion[],
  earliestRelevantSource: TemporalFinding,
): OriginAssessment {
  const originalEvent = originalEventFacet(snapshots, versions);
  const misinformationOrigin = misinformationOriginFacet(snapshots, versions);
  return {
    originalEvent,
    earliestRelevantSource,
    misinformationOrigin,
    likelyOriginCandidate: likelyOriginFacet(
      misinformationOrigin,
      earliestRelevantSource,
    ),
  };
}

